// TWO FALSIFIABLE CLAIMS FROM EINCOL ROUND 1, TESTED TOGETHER.
//
// CLAIM 1 (borrowed, quantum control). The reachable set of a bilinear system is
// generated by the LIE ALGEBRA of its control fields. Two fields with non-zero
// bracket reach states neither reaches alone. The auditor upheld the import:
// "an impulse (changing momentum) and a mass injection (changing the potential
// field) are non-commuting operators... a mathematically sound way to design
// combos and skill-based depth." PREDICTS: two impulses on one body along one
// axis add nothing; an impulse plus a displaced mass compound.
//
// CLAIM 2 (the auditor's pivot). "A game where every verb stabilizes is a
// Janitor Sim... the objective must shift from SURVIVAL to EQUILIBRIUM."
// PREDICTS: under a target-configuration objective, doing nothing well stops
// being competitive.
//
// The metric is renamed on the auditor's instruction: sd-of-outcome is LEVERAGE,
// not expansion. "Keeping the word expansion for the current metric is a
// category error that will lead to false positives like the DRAG result."
import { seedUniverse, stepUniverse, type Universe } from '../../game/dark/nbody.js';
import { fromFloat, toFloat } from '../../game/dark/fixed.js';

type Op = 'NONE' | 'IMP_A' | 'IMP_A2' | 'MASS_FAR';

function apply(u: Universe, op: Op, t: number): void {
  const b = u.bodies[0]!;
  if (op === 'IMP_A') b.vel = { ...b.vel, x: b.vel.x + fromFloat(t * 1.2) };
  else if (op === 'IMP_A2') b.vel = { ...b.vel, x: b.vel.x + fromFloat(t * 1.2) };
  else if (op === 'MASS_FAR') u.bodies.push({
    pos: { x: fromFloat(-3 + t * 6), y: fromFloat(2.2), z: fromFloat(0.8) },
    vel: { x: 0n, y: 0n, z: 0n }, mass: fromFloat(1.1),
  });
}

/** A VECTOR outcome, because a scalar makes the reachable set an interval. */
function outcome(u: Universe): number[] {
  let cx=0, cy=0, cz=0, m=0;
  for (const b of u.bodies) { const w=toFloat(b.mass); cx+=toFloat(b.pos.x)*w; cy+=toFloat(b.pos.y)*w; cz+=toFloat(b.pos.z)*w; m+=w; }
  cx/=m; cy/=m; cz/=m;
  let bound=0, inertia=0, maxr=0;
  for (const b of u.bodies) {
    const d = Math.hypot(toFloat(b.pos.x)-cx, toFloat(b.pos.y)-cy, toFloat(b.pos.z)-cz);
    if (d < 12) bound++;
    inertia += toFloat(b.mass) * d * d;
    maxr = Math.max(maxr, d);
  }
  return [bound / u.bodies.length, inertia / m, maxr];
}

const dist = (a: number[], b: number[]) => Math.hypot(a[0]!-b[0]!, (a[1]!-b[1]!)/40, (a[2]!-b[2]!)/20);

function run(seed: number, ops: readonly [Op, number][], horizon = 360): number[] {
  const u = seedUniverse(seed, 12);
  for (let s=0;s<80;s++) stepUniverse(u);
  apply(u, ops[0]![0], ops[0]![1]);
  for (let s=0;s<60;s++) stepUniverse(u);           // SEPARATED IN TIME -- a bracket
  if (ops[1]) apply(u, ops[1][0], ops[1][1]);       // needs the ops not to be simultaneous
  for (let s=0;s<horizon;s++) stepUniverse(u);
  return outcome(u);
}

console.log('── CLAIM 1 · do non-commuting pairs reach what neither reaches alone? ──');
console.log('pair                      | novel distance beyond the singles');
for (const [label, a, b] of [
  ['IMP_A then IMP_A (commuting)', 'IMP_A', 'IMP_A2'],
  ['IMP_A then MASS (bracket!=0)', 'IMP_A', 'MASS_FAR'],
] as [string, Op, Op][]) {
  let novel = 0, n = 0;
  for (const seed of [11,22,33]) {
    // The set each single verb can reach, swept over its own parameter.
    const singles: number[][] = [];
    for (let i=0;i<7;i++) { singles.push(run(seed, [[a, i/6]])); singles.push(run(seed, [[b, i/6]])); }
    // The pair, swept over both parameters.
    let worst = 0;
    for (let i=0;i<4;i++) for (let j=0;j<4;j++) {
      const p = run(seed, [[a, i/3],[b, j/3]]);
      worst = Math.max(worst, Math.min(...singles.map((s) => dist(p, s))));
    }
    novel += worst; n++;
  }
  console.log(`${label.padEnd(25)} | ${(novel/n).toFixed(4)}`);
}

console.log('');
console.log('── CLAIM 2 · does an EQUILIBRIUM objective beat competent inaction? ──');
// SURVIVAL: maximise bound fraction. EQUILIBRIUM: hold inertia inside a band.
const TARGET = 34, BAND = 6;
for (const [name, score] of [
  ['SURVIVAL  (bound fraction)', (o: number[]) => o[0]!],
  ['EQUILIBRIUM (inertia band)', (o: number[]) => Math.abs(o[1]! - TARGET) < BAND ? 1 : 0],
] as [string, (o:number[])=>number][]) {
  const rows: string[] = [];
  for (const [vn, v] of [['do-nothing','NONE'],['best mass','MASS_FAR'],['best impulse','IMP_A']] as [string,Op][]) {
    let best = 0, n = 0;
    for (const seed of [11,22,33]) {
      let b = 0;
      for (let i=0;i<7;i++) b = Math.max(b, score(run(seed, [[v, i/6]])));
      best += b; n++;
    }
    rows.push(`${vn} ${(best/n).toFixed(3)}`);
  }
  console.log(`${name.padEnd(27)} | ${rows.join('  ·  ')}`);
}
