// TWO FALSIFIABLE CLAIMS FROM EINCOL ROUND 1, TESTED TOGETHER.
//
// CLAIM 1 (borrowed, quantum control). The reachable set of a bilinear system is
// generated by the LIE ALGEBRA of its control fields. Two fields with non-zero
// bracket reach states neither reaches alone. The auditor upheld the import:
// "an impulse (changing momentum) and a mass injection (changing the potential
// field) are non-commuting operators... a mathematically sound way to design
// combos and skill-based depth." PREDICTS: two impulses on one body along one
// axis add nothing; an impulse plus a displaced mass compound.
//
// CLAIM 2 (the auditor's pivot). "A game where every verb stabilizes is a
// Janitor Sim... the objective must shift from SURVIVAL to EQUILIBRIUM."
// PREDICTS: under a target-configuration objective, doing nothing well stops
// being competitive.
//
// The metric is renamed on the auditor's instruction: sd-of-outcome is LEVERAGE,
// not expansion. "Keeping the word expansion for the current metric is a
// category error that will lead to false positives like the DRAG result."
import { seedUniverse, stepUniverse, type Universe } from '../../game/dark/nbody.js';
import { fromFloat, toFloat } from '../../game/dark/fixed.js';

type Op = 'NONE' | 'IMP_A' | 'IMP_A2' | 'MASS_FAR';

function apply(u: Universe, op: Op, t: number): void {
  const b = u.bodies[0]!;
  if (op === 'IMP_A') b.vel = { ...b.vel, x: b.vel.x + fromFloat(t * 1.2) };
  else if (op === 'IMP_A2') b.vel = { ...b.vel, x: b.vel.x + fromFloat(t * 1.2) };
  else if (op === 'MASS_FAR') u.bodies.push({
    pos: { x: fromFloat(-3 + t * 6), y: fromFloat(2.2), z: fromFloat(0.8) },
    vel: { x: 0n, y: 0n, z: 0n }, mass: fromFloat(1.1),
  });
}

/** A VECTOR outcome, because a scalar makes the reachable set an interval. */
function outcome(u: Universe): number[] {
  let cx=0, cy=0, cz=0, m=0;
  for (const b of u.bodies) { const w=toFloat(b.mass); cx+=toFloat(b.pos.x)*w; cy+=toFloat(b.pos.y)*w; cz+=toFloat(b.pos.z)*w; m+=w; }
  cx/=m; cy/=m; cz/=m;
  let bound=0, inertia=0, maxr=0;
  for (const b of u.bodies) {
    const d = Math.hypot(toFloat(b.pos.x)-cx, toFloat(b.pos.y)-cy, toFloat(b.pos.z)-cz);
    if (d < 12) bound++;
    inertia += toFloat(b.mass) * d * d;
    maxr = Math.max(maxr, d);
  }
  return [bound / u.bodies.length, inertia / m, maxr];
}

const dist = (a: number[], b: number[]) => Math.hypot(a[0]!-b[0]!, (a[1]!-b[1]!)/40, (a[2]!-b[2]!)/20);

function run(seed: number, ops: readonly [Op, number][], horizon = 360): number[] {
  const u = seedUniverse(seed, 12);
  for (let s=0;s<80;s++) stepUniverse(u);
  apply(u, ops[0]![0], ops[0]![1]);
  for (let s=0;s<60;s++) stepUniverse(u);           // SEPARATED IN TIME -- a bracket
  if (ops[1]) apply(u, ops[1][0], ops[1][1]);       // needs the ops not to be simultaneous
  for (let s=0;s<horizon;s++) stepUniverse(u);
  return outcome(u);
}

// ── CLAIM 1, SECOND ATTEMPT. THE FIRST TEST WAS CONFOUNDED BY RANGE. ───────
//
// It reported the COMMUTING pair reaching 2.3109 of novel distance against the
// non-commuting pair's 0.2127 -- ten times larger, and exactly backwards from
// the prediction. The cause was not physics. IMP_A and IMP_A2 are the SAME
// operator, so sweeping both parameters reaches a total impulse of 2.4 where a
// single verb swept over its own range reaches only 1.2. The "pair" was simply a
// wider sweep of one dial, and the extra distance was range, not composition.
//
// So the budget is held CONSTANT and only the composition varies: every line
// below spends the same total parameter, split differently in time and across
// operators. That is the only way the Lie-bracket question can be asked.
console.log('── CLAIM 1 (budget held constant) · does composition reach new states? ──');
console.log('composition                        | novel distance beyond single-verb set');
{
  const BUDGET = 1;
  for (const [label, ops] of [
    ['all at once, one operator', 'SINGLE'],
    ['split in time, SAME operator', 'SAME'],
    ['split in time, DIFFERENT operators', 'MIXED'],
  ] as [string, 'SINGLE' | 'SAME' | 'MIXED'][]) {
    let novel = 0, n = 0;
    for (const seed of [11, 22, 33]) {
      // The reference set: what either verb alone reaches at full budget.
      const singles: number[][] = [];
      for (let i = 0; i <= 6; i += 1) {
        singles.push(run(seed, [['IMP_A', (i / 6) * BUDGET]]));
        singles.push(run(seed, [['MASS_FAR', (i / 6) * BUDGET]]));
      }
      let worst = 0;
      for (let k = 1; k < 6; k += 1) {
        const t = (k / 6) * BUDGET;
        const rest = BUDGET - t;
        let p: number[];
        if (ops === 'SINGLE') p = run(seed, [['IMP_A', BUDGET]]);
        else if (ops === 'SAME') p = run(seed, [['IMP_A', t], ['IMP_A2', rest]]);
        else p = run(seed, [['IMP_A', t], ['MASS_FAR', rest]]);
        worst = Math.max(worst, Math.min(...singles.map((sg) => dist(p, sg))));
      }
      novel += worst; n += 1;
    }
    console.log(`${label.padEnd(34)} | ${(novel / n).toFixed(4)}`);
  }
}

console.log('');
console.log('── CLAIM 2 · does an EQUILIBRIUM objective beat competent inaction? ──');
// SURVIVAL: maximise bound fraction. EQUILIBRIUM: hold inertia inside a band.
const TARGET = 34, BAND = 6;
for (const [name, score] of [
  ['SURVIVAL  (bound fraction)', (o: number[]) => o[0]!],
  ['EQUILIBRIUM (inertia band)', (o: number[]) => Math.abs(o[1]! - TARGET) < BAND ? 1 : 0],
] as [string, (o:number[])=>number][]) {
  const rows: string[] = [];
  for (const [vn, v] of [['do-nothing','NONE'],['best mass','MASS_FAR'],['best impulse','IMP_A']] as [string,Op][]) {
    let best = 0, n = 0;
    for (const seed of [11,22,33]) {
      let b = 0;
      for (let i=0;i<7;i++) b = Math.max(b, score(run(seed, [[v, i/6]])));
      best += b; n++;
    }
    rows.push(`${vn} ${(best/n).toFixed(3)}`);
  }
  console.log(`${name.padEnd(27)} | ${rows.join('  ·  ')}`);
}
