// GENERATED by scripts/gen-rules-manifest.mjs — do not edit.
//
// The rules hash of the sources listed in RULE_SOURCES, pinned so the browser
// bundle can publish it in a commitment without reading the filesystem.
// verify-ruleset R7 fails the build if this drifts from computeRules().

export const RULES_HASH = 'f61cf6b2ef8c15f6be040bf199635e9d0728cb67a9d408c4800eb731464ebba5';

/** The pinned rules hash. Named for symmetry with computeRules(). */
export function computeRulesFromManifest(): string {
  return RULES_HASH;
}
