// GENERATED by scripts/gen-rules-manifest.mjs — do not edit.
//
// The rules hash of the sources listed in RULE_SOURCES, pinned so the browser
// bundle can publish it in a commitment without reading the filesystem.
// verify-ruleset R7 fails the build if this drifts from computeRules().

export const RULES_HASH = '5af4861852a8d7f0e0d635b7816e1cbbb258f95516d15276d7781babc61aa9c4';

/** The pinned rules hash. Named for symmetry with computeRules(). */
export function computeRulesFromManifest(): string {
  return RULES_HASH;
}
