// GENERATED by scripts/gen-rules-manifest.mjs — do not edit.
//
// The rules hash of the sources listed in RULE_SOURCES, pinned so the browser
// bundle can publish it in a commitment without reading the filesystem.
// verify-ruleset R7 fails the build if this drifts from computeRules().

export const RULES_HASH = '6551340a9d11439b260f730b07d2a6982bb612a7c8a4dd918e8348c12327fd41';

/** The pinned rules hash. Named for symmetry with computeRules(). */
export function computeRulesFromManifest(): string {
  return RULES_HASH;
}
